[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
build_src_flags = -O0
build_flags = -I$PROJECT_SRC_DIR/../include 
    -I lib/tinyusb/src 
    -I lib/tinyusb/hw
lib_deps = 
    tinyusb
lib_ldf_mode = chain+
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200